# Generated by Django 5.2.10 on 2026-04-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_alter_alert_alert_type_weapon'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadDamageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(blank=True, default='', max_length=160, verbose_name='Route')),
                ('source_type', models.CharField(default='unknown', max_length=32, verbose_name='Source type')),
                ('source_ref', models.CharField(blank=True, default='', max_length=600, verbose_name='Source ref')),
                ('annotated_image', models.CharField(blank=True, default='', max_length=600, verbose_name='Image annotee')),
                ('heatmap_image', models.CharField(blank=True, default='', max_length=600, verbose_name='Heatmap XAI')),
                ('verdict', models.CharField(default='no_damage', max_length=32, verbose_name='Verdict')),
                ('risk_score', models.FloatField(default=0.0, verbose_name='Score risque')),
                ('risk_level', models.CharField(default='low', max_length=32, verbose_name='Niveau risque')),
                ('confidence_max', models.FloatField(default=0.0, verbose_name='Confiance max')),
                ('damage_ratio', models.FloatField(default=0.0, verbose_name='Ratio dommages')),
                ('priority', models.CharField(default='medium', max_length=32, verbose_name='Priorite maintenance')),
                ('estimated_budget_min', models.PositiveIntegerField(default=0, verbose_name='Budget min')),
                ('estimated_budget_max', models.PositiveIntegerField(default=0, verbose_name='Budget max')),
                ('action_plan', models.JSONField(blank=True, default=list, verbose_name="Plan d'action")),
                ('quality', models.JSONField(blank=True, default=dict, verbose_name='Qualite donnees')),
                ('xai_summary', models.JSONField(blank=True, default=dict, verbose_name='XAI')),
                ('llm_report', models.TextField(blank=True, default='', verbose_name='Rapport LLM')),
                ('ticket_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Ticket maintenance')),
                ('ticket_deadline_days', models.PositiveSmallIntegerField(default=30, verbose_name='Delai ticket (jours)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('anti_fp_flag', models.BooleanField(default=False, verbose_name='Anti faux-positifs corrige')),
                ('pdf_report_path', models.CharField(blank=True, default='', max_length=600, verbose_name='PDF rapport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analyse road damage',
                'verbose_name_plural': 'Analyses road damage',
                'ordering': ['-created_at'],
            },
        ),
    ]
