# Generated by Django 5.2.13 on 2026-05-02 02:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_roaddamageanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenReclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='reclamations/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'mp4', 'mov', 'm4v'])], verbose_name='Média')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Vidéo')], max_length=10, verbose_name='Type média')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('category', models.CharField(choices=[('pothole', 'Nid de poule'), ('garbage', 'Déchets'), ('smoke', 'Fumée'), ('flood', 'Inondation')], max_length=20, verbose_name='Catégorie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Réclamation citoyenne',
                'verbose_name_plural': 'Réclamations citoyennes',
                'ordering': ['-created_at'],
            },
        ),
    ]
