# Generated by Django 5.2.13 on 2026-05-03 17:50

import django.core.validators
import django.db.models.deletion
import monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_citizenreclamation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=96, unique=True)),
                ('display_name', models.CharField(max_length=160, verbose_name='Nom affiché')),
                ('person_code', models.CharField(blank=True, default='', help_text='Référence métier locale (badge, dossier…) — aucun lien légal garanti hors cadre légal RGPD/local.', max_length=64, verbose_name='Code / matricule (fictif ou réel)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif dans la recherche')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Identité faciale',
                'verbose_name_plural': 'Identités faciales',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='FaceReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=monitoring.models.upload_face_registry_reference, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Photo référence')),
                ('is_primary', models.BooleanField(default=False, help_text='Indique une photo favorisée (affichage admin / UI futures).', verbose_name='Principale')),
                ('embedding', models.JSONField(blank=True, help_text='Rempli automatiquement (DeepFace) lors de la sauvegarde si activé.', null=True, verbose_name='Vecteur d’embedding')),
                ('embedding_model', models.CharField(blank=True, default='', max_length=64, verbose_name='Modèle d’embedding')),
                ('embedding_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('face_identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='monitoring.faceidentity', verbose_name='Identité')),
            ],
            options={
                'verbose_name': 'Photo référence visage',
                'verbose_name_plural': 'Photos références visages',
                'ordering': ['-is_primary', '-pk'],
            },
        ),
    ]
