# Generated by Django 5.2.13 on 2026-05-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_face_identity_category_facepersonprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireCameraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esp_ip', models.CharField(blank=True, default='', max_length=128, verbose_name='IP ESP32-CAM')),
                ('ui_prefs', models.JSONField(blank=True, default=dict, verbose_name='Préférences (JSON)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration caméra feu ESP32',
                'verbose_name_plural': 'Configuration caméra feu ESP32',
            },
        ),
    ]
