# Generated by Django 5.2.13 on 2026-05-05 03:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_firecameraconfig_road_live_vision'),
    ]

    operations = [
        migrations.CreateModel(
            name='WasteStreetReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image', models.ImageField(blank=True, null=True, upload_to='waste_reports/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Image téléversée')),
                ('source_image_url', models.URLField(blank=True, default='', max_length=1024, verbose_name='URL image source')),
                ('annotated_image_url', models.CharField(blank=True, default='', max_length=512, verbose_name='URL image annotée')),
                ('location', models.CharField(blank=True, default='', max_length=400, verbose_name='Ville / adresse / zone')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('detected_objects', models.JSONField(blank=True, default=list, verbose_name='Détections')),
                ('object_count', models.PositiveIntegerField(default=0, verbose_name='Nombre d’objets')),
                ('max_confidence', models.FloatField(default=0.0, verbose_name='Confiance max')),
                ('sms_status', models.CharField(choices=[('pending', 'En attente'), ('mock_sent', 'SMS simulé (mock)'), ('sent', 'SMS envoyé (Twilio)'), ('failed', 'Échec envoi')], default='pending', max_length=24, verbose_name='Statut SMS')),
                ('sms_body', models.TextField(blank=True, default='', verbose_name='Texte SMS')),
                ('sms_twilio_sid', models.CharField(blank=True, default='', max_length=64, verbose_name='Twilio SID')),
                ('sms_detail', models.TextField(blank=True, default='', verbose_name='Détail SMS / erreur')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rapport déchets rue',
                'verbose_name_plural': 'Rapports déchets rue',
                'ordering': ['-created_at'],
            },
        ),
    ]
