# Generated by Django 5.2.13 on 2026-05-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0015_waste_report_expand'),
    ]

    operations = [
        migrations.CreateModel(
            name='UavStructuralAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('primary_filename', models.CharField(default='', max_length=260, verbose_name='Fichier image UAV')),
                ('comparison_filename', models.CharField(blank=True, default='', max_length=260, verbose_name='Image comparaison')),
                ('zone', models.CharField(choices=[('A', 'Zone A'), ('B', 'Zone B'), ('C', 'Zone C')], default='B', max_length=4, verbose_name='Zone')),
                ('surface_m2', models.FloatField(default=0.0, verbose_name='Surface estimée (m²)')),
                ('prediction_index', models.PositiveSmallIntegerField(default=0)),
                ('prediction_label', models.CharField(default='', max_length=64)),
                ('probabilities', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('comparison_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comparison_label', models.CharField(blank=True, default='', max_length=64)),
                ('comparison_probabilities', models.JSONField(blank=True, default=list)),
                ('comparison_confidence', models.FloatField(blank=True, null=True)),
                ('primary_original_url', models.CharField(blank=True, default='', max_length=512)),
                ('primary_gradcam_url', models.CharField(blank=True, default='', max_length=512)),
                ('primary_saliency_url', models.CharField(blank=True, default='', max_length=512)),
                ('comparison_original_url', models.CharField(blank=True, default='', max_length=512)),
                ('comparison_gradcam_url', models.CharField(blank=True, default='', max_length=512)),
                ('comparison_saliency_url', models.CharField(blank=True, default='', max_length=512)),
                ('risk_score', models.FloatField(default=0.0)),
                ('operational_level', models.CharField(blank=True, default='', max_length=32)),
                ('operational_level_key', models.CharField(blank=True, default='', max_length=24)),
                ('co2_estimate_kg', models.FloatField(default=0.0)),
                ('recommendations', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Analyse UAV (structure)',
                'verbose_name_plural': 'Analyses UAV (structure)',
                'ordering': ['-created_at'],
            },
        ),
    ]
