# Generated by Django 5.2.13 on 2026-05-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_uav_structural_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIInferenceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_key', models.CharField(db_index=True, help_text='Ex. groq:llama-3.3-70b, local:yolov8n.pt', max_length=120, verbose_name='Clé modèle')),
                ('model_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Nom affiché')),
                ('provider', models.CharField(blank=True, default='', max_length=64, verbose_name='Fournisseur')),
                ('operation', models.CharField(blank=True, default='', help_text='groq_chat, fusion_analyze_frame, sightengine_image…', max_length=80, verbose_name='Opération')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (ms)')),
                ('success', models.BooleanField(default=True, verbose_name='Succès')),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP status')),
                ('error_message', models.CharField(blank=True, default='', max_length=500, verbose_name='Erreur')),
            ],
            options={
                'verbose_name': 'Journal inférence IA',
                'verbose_name_plural': 'Journal inférences IA',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'model_key'], name='monitoring__created_c5494c_idx')],
            },
        ),
    ]
